# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06d0d4d550eec64a2db657a28a0641242c05d2ac036eab002015295526bba0f976a7649a17a624920e0bf832320f5492a4de19f9a7c081c1c766a3e442e26cfd

test:
  secret_key_base: eefb0378a925b031e44c5847915fc485011aa2585434afc1a5f8ee9668335f666c657da9d1f5e030f3e74671c1bb3b13a42e7f9976096fcf671483b6d20b1b7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
